project:
  type: website
  output-dir: docs

website:
  title: "Yushun's website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Resume"
        menu:
          - resume.qmd
          - resume_FR.qmd 
          - resume_ZH.qmd 

      - publication.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



